name: Docker Build and Push

on:
    push:
        branches:
            - main
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.24'
            
            - name: Run tests
              run: go test ./...
            
            - name: Make file to executable
              run: chmod +x deploy.sh
            
            - name: Build project
              run: ./deploy.sh
